server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://192.168.1.12:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册消息，默认为 true ，单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡 
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka # 单机
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka