server:
  port: 3344

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/solvayshpere/sprincloud-config.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: rabbit.solvay.com
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'